package com.tommy.model;

// Generated 2014/5/11 �U�� 08:48:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Place generated by hbm2java
 */
@Entity
@Table(name = "place", catalog = "user")
public class Place {

	private String name;
	private String postNo;
	private String address;
	private String latitude;
	private String longtitude;
	private String phone;

	public Place() {
	}

	public Place(String name, String postNo, String address, String latitude,
			String longtitude, String phone) {
		this.name = name;
		this.postNo = postNo;
		this.address = address;
		this.latitude = latitude;
		this.longtitude = longtitude;
		this.phone = phone;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "POSTNO")
	public String getPostNo() {
		return this.postNo;
	}

	public void setPostNo(String postNo) {
		this.postNo = postNo;
	}

	@Column(name = "ADDRESS")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "LATITUDE")
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "LONGTITUDE")
	public String getLongtitude() {
		return this.longtitude;
	}

	public void setLongtitude(String longtitude) {
		this.longtitude = longtitude;
	}

	@Column(name = "PHONE")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}


}
